main_app/urls.py
from django.urls import path
from .views import index, signup, logOut
from django.contrib.auth import views as log_views


from .forms import LoginForm
app_name = 'main_app'
urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', log_views.LoginView.as_view(template_name='main_app/login.html', authentication_form=LoginForm), name='login'),
    path('logout/',logOut, name='logout')
    
]

projects/urls.py
from django.urls import path 
from . import views

app_name = 'projects'

urlpatterns = [
    path('<int:pk>/', views.detali, name='detail')
]

sms/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('projects/', include('projects.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main_app/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Classname(models.Model):
    name = models.CharField(max_length=255)
    Lecturer = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class Workname(models.Model):
    name = models.CharField(max_length=255)
    classname = models.ForeignKey(Classname, related_name='items', on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    submitted_on = models.DateTimeField(blank=True, null=True)
    mark_done = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

CLASSES = 'shadow appearance-none border rounded-2xl w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':'shadow appearance-none border rounded-2xl w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
    }))
        
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Password',
        'class':'shadow appearance-none border rounded-2xl w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
    }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email',
        'class':CLASSES
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Password',
        'class':CLASSES
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Retype Password',
        'class':CLASSES
    }))

main_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import *
from projects.models import *
from django.contrib.auth import logout

# Create your views here.
@login_required(login_url='/login/')
def index(request):
    work = Workname.objects.filter(mark_done = False)[0:6]
    category = Category.objects.all()
    return render(request, 'main_app/index.html',{
        'work':work,
        'project':category
    } )


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'main_app/signup.html', {
        'form':form
    })


def logOut(request):
    logout(request)
    return redirect('/login/')
    

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Workname

# Create your views here.

def detali(request, pk):
    work = get_object_or_404(Workname, pk=pk)

    return render(request, 'projects/detail.html', {
        'work':work
    })

main_app/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %} | BHUclassrooms</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="bg-blue-100">
    <nav class="bg-gray-800">
      <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 items-center justify-between">
          <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            <!-- Mobile menu button-->
            <button
              type="button"
              class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
              aria-controls="mobile-menu"
              aria-expanded="false"
            >
              <span class="absolute -inset-0.5"></span>
              <span class="sr-only">Open main menu</span>
              <!--
                  Icon when menu is closed.
      
                  Menu open: "hidden", Menu closed: "block"
                -->
              <svg
                class="block h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                />
              </svg>
              <!--
                  Icon when menu is open.
      
                  Menu open: "block", Menu closed: "hidden"
                -->
              <svg
                class="hidden h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
          <div
            class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start"
          >
            <div class="flex flex-shrink-0 items-center">
              <a href="/"
                ><p class="text-lg text-bold text-white">BHU Classrooms</p></a
              >
            </div>
            <div class="hidden sm:ml-6 sm:block">
              <div class="flex space-x-4">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <a
                  href="/"
                  class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium"
                  aria-current="page"
                  >Dashboard</a
                >
                <a
                  href="#"
                  class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                  >My Classes</a
                >
                <a
                  href="#"
                  class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                  >Projects</a
                >
                <a
                  href="#"
                  class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                  >Calendar</a
                >
                {% if request.user.is_staff %}
                <a
                  href="#"
                  class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                  >Create Assignment</a
                >
                <a
                  href="#"
                  class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                  >Create Classroom</a
                >
                {% endif %}
              </div>
            </div>
          </div>
          <div
            class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
          >
            <button
              type="button"
              class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
            >
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">View notifications</span>
              <svg
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"
                />
              </svg>
            </button>

            <!-- Profile dropdown -->
            <div class="relative ml-3">
              <div>
                <button
                  type="button"
                  class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                  id="user-menu-button"
                  aria-expanded="false"
                  aria-haspopup="true"
                >
                  <span class="absolute -inset-1.5"></span>
                  <span class="sr-only">Open user menu</span>
                  <!-- <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt=""> -->
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    height="16"
                    width="14"
                    viewBox="0 0 448 512"
                    class="h-8 w-8 rounded-xl"
                  >
                    <path
                      d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"
                    />
                  </svg>
                </button>
              </div>

              <!--
                  Dropdown menu, show/hide based on menu state.
      
                  Entering: "transition ease-out duration-100"
                    From: "transform opacity-0 scale-95"
                    To: "transform opacity-100 scale-100"
                  Leaving: "transition ease-in duration-75"
                    From: "transform opacity-100 scale-100"
                    To: "transform opacity-0 scale-95"
                -->
              <div
                class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-gray-900 py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden"
                id="user-menu"
                role="menu"
                aria-orientation="vertical"
                aria-labelledby="user-menu-button"
                tabindex="-1"
              >
                <!-- Active: "bg-gray-100", Not Active: "" -->
                <a
                  href="#"
                  class="block px-4 py-2 text-sm text-white"
                  role="menuitem"
                  tabindex="-1"
                  id="user-menu-item-0"
                  >Your Profile</a
                >
                <a
                  href="#"
                  class="block px-4 py-2 text-sm text-white"
                  role="menuitem"
                  tabindex="-1"
                  id="user-menu-item-1"
                  >Settings</a
                >
                {% if request.user.is_authenticated %}
                <a
                  href="{% url 'main_app:logout' %}"
                  class="block px-4 py-2 text-sm text-white"
                  role="menuitem"
                  tabindex="-1"
                  id="user-menu-item-2"
                  >Sign out</a
                >
                {% else %}
                <a
                  href="{% url 'main_app:login' %}"
                  class="block px-4 py-2 text-sm text-white"
                  role="menuitem"
                  tabindex="-1"
                  id="user-menu-item-2"
                  >Sign in</a
                >
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="sm:hidden hidden" id="mobile-menu">
        <div class="space-y-1 px-2 pb-3 pt-2">
          <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
          <a
            href="/"
            class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium"
            aria-current="page"
            >Dashboard</a
          >
          <a
            href="#"
            class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
            >My Classes</a
          >
          <a
            href="#"
            class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
            >Projects</a
          >
          <a
            href="#"
            class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
            >Calendar</a
          >
          {% if request.user.is_staff %}
          <a
            href="#"
            class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
            >Create Assignment</a
          >
          <a
            href="#"
            class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
            >Create Classroom</a
          >
          {% endif %}
        </div>
      </div>
    </nav>
    <script>
      // Function to handle dropdown menu visibility toggle
      function toggleDropdownMenu(menuId) {
        const menu = document.getElementById(menuId);
        if (menu.classList.contains("hidden")) {
          // Show the menu
          menu.classList.remove("hidden");
          menu.classList.add("block");
        } else {
          // Hide the menu
          menu.classList.remove("block");
          menu.classList.add("hidden");
        }
      }

      // Event listeners for dropdown buttons
      const userMenuButton = document.getElementById("user-menu-button");
      const mobileMenuButton = document.querySelector(
        '[aria-controls="mobile-menu"]'
      );

      userMenuButton.addEventListener("click", function () {
        toggleDropdownMenu("user-menu");
      });

      mobileMenuButton.addEventListener("click", function () {
        toggleDropdownMenu("mobile-menu");
      });
    </script>

    <div class="px-6 py-6">{% block content %} {% endblock %}</div>
    <div class="flex flex-col min-h-screen">
      <footer class="py-6 px-6 flex justify-between bg-gray-800 mt-auto">
        <div class="w-2/3 pr-10">
          <h3 class="mb-5 font-semibold text-blue-400">About</h3>
          <p class="text-lg text-blue-500">
            Lorem ipsum Bla Bla Bla Lorem ipsum Bla Bla Bla Lorem ipsum Bla Bla
            Bla
          </p>
        </div>

        <div class="w-1/3">
          <h3 class="mb-5 font-semibold text-blue-400">Menu</h3>
          <ul class="space-y-2">
            <span
              class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3"
            >
              <li>
                <a href="#" class="text-lg text-blue-500 hover:text-blue-200"
                  >About</a
                >
              </li>
              <li>
                <a href="#" class="text-lg text-blue-500 hover:text-blue-200"
                  >FAQs</a
                >
              </li>
              <li>
                <a href="#" class="text-lg text-blue-500 hover:text-blue-200"
                  >Need Help?</a
                >
              </li>
              <li>
                <a href="#" class="text-lg text-blue-500 hover:text-blue-200"
                  >Terms Of Use</a
                >
              </li>
            </span>
          </ul>
        </div>
      </footer>
    </div>
  </body>
</html>

main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="text-lg text-white-400 text-center">
        <p>
            Class Updates
        </p>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {% for item in work %}
                <div>
                    <a href="{% url 'projects:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>
                        <div class="rounded-b-xl p-6" style="background-color: aliceblue;">
                            <h2 class="text-gray-900 text-center text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-700 text-center text-lg">{{ item.created_at }}</p>
                            <p class="text-gray-700 text-center text-lg"><strong>Posted by: </strong>{{ item.created_by }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

main_app/templates/main_app/login.html
{% extends 'main_app/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="flex justify-center items-center bg-blue-100 p-6 rounded-2xl">
        <!-- <h1 class="mb-6 text-3xl">Login</h1> -->

        <form action="?next=/" method="post" class="bg-white shadow-md rounded-xl px-8 pt-6 pb-7 py-4 mb-4 w-full sm:w-1/2 lg:w-1/3">
            {% csrf_token %}

            <div class="">
                <div class="mb-4">
                    <div class="mb-3">
                        <label for="username" class="inline-block mb-2">Username</label><br>
                        {{ form.username }}
                    </div>
                </div>
<br>
                <div class="mb-6">
                    <div class="mb-3">
                        <label for="username" class="inline-block mb-2">Password</label><br>
                        {{ form.password }}
                    </div>
                </div>
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-3 bg-red-100 rounded-xl">
                    {% for field in form  %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-3 px-3 mx-auto text-lg bg-blue-500 hover:bg-blue-800 rounded-xl text-white transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">Login</button> OR
            <a href="{% url 'main_app:signup' %}" class="py-2 px-3 mx-auto ml-3 text-lg bg-blue-500 hover:bg-blue-800 rounded-xl text-white transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">Sign Up</a>
        </form>
    </div>
{% endblock %}

main_app/templates/main_app/signup.html
{% extends 'main_app/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="flex justify-center items-center px-6 py-6 bg-blue-100">
    <form action="." method="post" class="bg-white shadow-md rounded-xl px-8 pt-6 pb-8 mb-4 w-full sm:w-1/2 lg:w-1/3">
        {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
          Username
        </label>
        <!-- <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          id="username" type="text" placeholder="Enter your username"> -->
          {{ form.username }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
          Email
        </label>
        <!-- <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
          id="password" type="password" placeholder="********"> -->
          {{ form.email }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
          Type A Password
        </label>
        <!-- <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
          id="password" type="password" placeholder="********"> -->
          {{ form.password1 }}
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
          Retype Password
        </label>
        <!-- <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
          id="password" type="password" placeholder="********"> -->
          {{ form.password2 }}
      </div>
      {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-3 bg-red-100 rounded-xl">
          {% for field in form  %}
              {{ field.errors }}
          {% endfor %}
          {{ form.non_field_errors }}
      </div>
  {% endif %}
      <button class="py-3 px-3 mx-auto text-lg bg-blue-500 hover:bg-blue-800 rounded-xl text-white transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">sign up</button>
      <a href="{% url 'main_app:login' %}" class="py-4 px-3 mx-auto ml-3 text-lg bg-blue-500 hover:bg-blue-800 rounded-xl text-white transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">Log In</a>
    </form>
  </div>
{% endblock %}

projects/templates/projects/detail.html
{% extends 'main_app/base.html' %}
{% block title %}{{ work.name }}{% endblock %}

{% block content %}
    <div>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            <img src="{{ work.image.url }}" class="rounded-lg">
        </div><br>

        <div class="p-3 rounded-xl" style="background-color: aliceblue;">
            <h2 class="text-start text-2xl">Class:</h2>
            <p>{{ work.classname }}</p>
            <h2 class="text-2xl mb-6">{{ work.name }}</h2>
            <h2 class="text-base text-2xl text-start"><strong>Description:</strong></h2>
            <p>{{ work.description }}</p>
            <label for="category" class="text-base text-2xl text-start"><strong>Project Type:</strong></label>
            <p>{{ work.category }}</p>
            <label for="time_stamp" class="text-base text-2xl text-start"><strong>Posted at:</strong></label>
            <p>{{ work.created_at }}</p>
            {% if work.submitted_on %}
                <label for="submitted"><strong>To Be Submitted On:</strong> {{ work.submitted_on }}</label>
            {% else %}
                <label for="submitted"><strong>To Be Submitted On:</strong> null</label>
            {% endif %}
        </div>
    </div>
{% endblock %}